# hostname    connect   chatbot   dir          profile
clark2        -         argus     ~            bare
bevo2         -         argus     ~            bare
nas           autossh   argus     ~            bare
taylor        autossh   argus     ~            bare
