name: Tests

on:
  push:
    branches: [master, main]
  pull_request:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shell:
    uses: cgraf78/actions/.github/workflows/shell-ci.yml@feeba8dcb271bd206ae55cd735e53577ffa08877
    with:
      matrix-set: full
      setup: dotfiles
      test-command: .local/bin/dot-test

  termux:
    uses: cgraf78/actions/.github/workflows/termux-ci.yml@feeba8dcb271bd206ae55cd735e53577ffa08877
    with:
      command: |-
        pkg install -y git curl
        export CI=1 GITHUB_ACTIONS=1
        export HOME=$PWD
        export PATH="$HOME/.local/bin:$PATH"
        bash .local/bin/dot update --skip-pull
        bash .local/bin/dot doctor
